//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BettingRoom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Games = new HashSet<Game>();
            this.Games1 = new HashSet<Game>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SportName { get; set; }
        public int LeagueId { get; set; }
        public int PointsInLeague { get; set; }
        public Nullable<double> TeamOdds { get; set; }
    
        public virtual ICollection<Game> Games { get; set; }
        public virtual ICollection<Game> Games1 { get; set; }
        public virtual League League { get; set; }
    }
}
